name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Person API.json" -e "15870526-c02191e4-f394-4557-a00e-6c045392902d" --integration-id "168475-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint 5e487f73-9042-4ee0-8c7c-45f1b7f28668 --integration-id 168475
